config/routes.rb
Rails.application.routes.draw do

  # root
  root 'static_pages#home'

  # signups
  get 'users/new'  => 'users#new', as: :user_signup
  post 'users'  => 'users#create'
  get 'bands/new'  => 'bands#new', as: :band_signup
  post 'bands'  => 'bands#create'

  # sessions
  get 'user_login' => 'sessions#user_login', as: :user_login
  post 'user_login' => 'sessions#user_create'
  get 'band_login' => 'sessions#band_login', as: :band_login
  post 'band_login' => 'sessions#band_create'
  delete 'logout' => 'sessions#destroy'
  resources :account_activations, only: [:edit]

  # password reset
  resources :user_password_resets, only: [:new, :create, :edit, :update]
  resources :band_password_resets, only: [:new, :create, :edit, :update]

  # main pages
  resources :concert_lists
  resources :concerts
  resources :bands, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :fans
    end
    collection do
      get :sorted_by_genre
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :favorite_bands, :concerts
      get :concert_lists
      get :feed
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :fanships, only: [:create, :destroy]
  resources :concert_goings, only: [:create, :edit, :update, :destroy]
  resources :genres
  resources :searches

  # static pages
  get  'home' => 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token, :genre_ids

  before_save :downcase_email

	has_many :fanships, foreign_key: :fan_id, dependent: :destroy
	has_many :favorite_bands, through: :fanships, source: :band

	has_many :concert_goings, foreign_key: :goer_id
	has_many :concerts, through: :concert_goings

	has_many :active_relationships, class_name:  "UserRelationship", foreign_key: :follower_id, dependent: :destroy
	has_many :passive_relationships, class_name:  "UserRelationship", foreign_key: :followed_id, dependent: :destroy

	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships

  has_many :user_likes_genres
  has_many :favorite_genres, through: :user_likes_genres, source: :genre

	has_many :concert_lists, foreign_key: :list_owner_id, dependent: :destroy

  has_secure_password

  before_save { self.email = email.downcase }

  validates :username,  presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :reputation_score, numericality: { only_integer: true, less_than_or_equal_to: 10 }

  # Retrieve all concerts that have bands who play genres that the user likes, which have been included in recommended lists of users he follows
  def concerts_from_followed_users_who_like_the_same_genres
    following_ids = "SELECT user_relationships.followed_id FROM user_relationships WHERE user_relationships.follower_id = :user_id"
    list_owner_ids = "SELECT users2.id FROM users users2 WHERE users2.id IN (#{following_ids})"
    concert_list_ids = "SELECT concert_lists.id FROM concert_lists WHERE concert_lists.list_owner_id IN (#{list_owner_ids})"
    recommended_concert_ids = "SELECT recommendations2.id FROM recommendations recommendations2 WHERE recommendations2.concert_list_id IN (#{concert_list_ids})"
    genre_ids = "SELECT genres2.genre FROM genres genres2 INNER JOIN user_likes_genres ON (user_likes_genres.genre_id = genres2.id) INNER JOIN users ON (users.id = user_likes_genres.user_id) WHERE users.id = :user_id"
    concert_ids = 
    "SELECT concerts2.id FROM concerts concerts2 INNER JOIN recommendations ON (recommendations.concert_id = concerts2.id) INNER JOIN lineups ON (lineups.concert_id = concerts2.id) INNER JOIN bands ON (bands.id = lineups.band_id) INNER JOIN band_plays_genres ON (band_plays_genres.band_id = bands.id) INNER JOIN genres ON (genres.id = band_plays_genres.genre_id) WHERE genres.genre IN (#{genre_ids}) AND concerts2.id IN (#{recommended_concert_ids})"
    Concert.where("id IN (#{concert_ids})", user_id: self.id)
  end

  # Retrieve all concerts that have bands who play genres that the user likes, which have been included in at least 4 recommended lists

  def popular_concerts_from_users_who_like_the_same_genres
    genre_ids = "SELECT genres2.genre FROM genres genres2 INNER JOIN user_likes_genres ON (user_likes_genres.genre_id = genres2.id) INNER JOIN users ON (users.id = user_likes_genres.user_id) WHERE users.id = :user_id"
    concert_ids = "SELECT concerts2.id FROM concerts concerts2 INNER JOIN recommendations ON (recommendations.concert_id = concerts2.id) INNER JOIN lineups ON (lineups.concert_id = concerts2.id) INNER JOIN bands ON (bands.id = lineups.band_id) INNER JOIN band_plays_genres ON (band_plays_genres.band_id = bands.id) INNER JOIN genres ON (genres.id = band_plays_genres.genre_id) WHERE genres.genre IN (#{genre_ids}) GROUP BY concerts2.id, recommendations.concert_list_id HAVING COUNT(*) >= 10"
    Concert.where("id IN (#{concert_ids})", user_id: self.id)
  end

  # Retrieve the 3 top recommended concerts
  def top_recommended_concerts
    concert_ids = "SELECT concerts2.id FROM concerts concerts2 INNER JOIN recommendations ON (recommendations.concert_id = concerts2.id) GROUP BY concerts2.id HAVING COUNT(*) >= 10 ORDER BY COUNT(*) DESC LIMIT 3"
    concert_ids_fix = "SELECT c1.id FROM concerts c1 INNER JOIN (#{concert_ids}) c2 ON (c1.id = c2.id)"
    Concert.where("id IN (#{concert_ids_fix})")
  end

  # Retrieve all concerts recommended by some user who have at least 3 favorite genres in common
  def concerts_recommended_by_users_with_similar_tastes
    genre_ids = "SELECT genres2.id FROM genres genres2 INNER JOIN user_likes_genres user_likes_genres2 ON (user_likes_genres2.genre_id = genres2.id) INNER JOIN users ON (users.id = user_likes_genres2.user_id) WHERE users.id = :user_id"
    user_ids = "SELECT users2.id FROM users users2 INNER JOIN user_likes_genres ON (user_likes_genres.user_id = users2.id) INNER JOIN genres ON (genres.id = user_likes_genres.genre_id) WHERE genres.id IN (#{genre_ids}) GROUP BY users2.id HAVING COUNT(*) >= 3"
    concert_ids = "SELECT DISTINCT recommendations.concert_id FROM recommendations INNER JOIN concert_lists ON (concert_lists.id = recommendations.concert_list_id) INNER JOIN users users3 ON (users3.id = concert_lists.list_owner_id) WHERE users3.id IN (#{user_ids})"
    Concert.where("id IN (#{concert_ids})", user_id: self.id)
  end

  # Retrieve all bands who play genres that the user likes and that have at least 10 other fans
  def popular_bands_that_play_genres_the_user_like
    genre_ids = "SELECT genres2.genre FROM genres genres2 INNER JOIN user_likes_genres ON (user_likes_genres.genre_id = genres2.id) INNER JOIN users ON (users.id = user_likes_genres.user_id) WHERE users.id = :user_id"
    band_ids = "SELECT bands2.id FROM bands bands2 INNER JOIN fanships ON (fanships.band_id = bands2.id) INNER JOIN band_plays_genres ON (band_plays_genres.band_id = bands2.id) INNER JOIN genres ON (genres.id = band_plays_genres.genre_id) WHERE genres.genre IN (#{genre_ids}) GROUP BY fanships.band_id HAVING COUNT(*) >= 10"
    Band.where("id IN (#{band_ids})", user_id: User.first.id)
  end

  # Retrieve all bands who have had at least 1 concerts with average ratings greater or equal than 4
  def bands_with_good_concerts_that_play_genres_the_user_like
    genre_ids = "SELECT genres2.genre FROM genres genres2 INNER JOIN user_likes_genres ON (user_likes_genres.genre_id = genres2.id) INNER JOIN users ON (users.id = user_likes_genres.user_id) WHERE users.id = 1"
    band_ids = "SELECT DISTINCT bands2.id FROM bands bands2 INNER JOIN lineups ON (lineups.band_id = bands2.id) INNER JOIN concerts ON (concerts.id = lineups.concert_id) INNER JOIN concert_goings ON (concert_goings.concert_id = concerts.id) INNER JOIN band_plays_genres ON (band_plays_genres.band_id = bands2.id) INNER JOIN genres ON (genres.id = band_plays_genres.genre_id) WHERE genres.genre IN (#{genre_ids}) AND concert_goings.rating IS NOT NULL GROUP BY concert_goings.concert_id HAVING AVG(concert_goings.rating) >= 4"
    Band.where("id IN (#{band_ids})", user_id: User.first.id)
  end

  def set_genre(genre)
    user_likes_genres.create(genre_id: genre.id)
  end

  def likes_genre?(genre)
    self.genres.include?(genre)
  end

  # Genres that band plays.
  def likes_genres
    genres = Array.new
    self.favorite_genres.each do |genre|
      genres << genre.printable
    end
    genres.uniq
  end

  # Set reputation score.
  def set_reputation_score
    unless self.reputation_score == 10
      score = 0
      # If the user has created his account more than 1 week ago, then he will be awarded 1 point.
      score += 1 if self.created_at < Time.now.days_ago(7)
      # If the user has created his account more than 1 month ago, then he will be awarded 1 point.
      score += 1 if self.created_at < Time.now.days_ago(30)
      # For each concert review a user has made, he is awarded 1 point.
      number_of_reviews = 0
      self.concert_goings.each do |concert_going|
        number_of_reviews += 1 if concert_going.review 
      end
      score += number_of_reviews
      # For each concert recommendation a user has made, he is awarded 1 point.
      score += self.concert_lists.count

      self.reputation_score = (score > 10 ? 10 : score)
    end
  end

  # User can edit concerts.
  def can_edit_concerts?
    self.reputation_score >= 8 || self.is_admin?
  end

  # User can recommend concert lists.
  def can_recommend?
    self.reputation_score >= 1 || self.is_admin?
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

	# Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Become fan of a band.
  def become_fan(band)
    fanships.create(band_id: band.id)
  end

  # Not a fan of the band anymore.
  def undo_become_fan(band)
    fanships.find_by(band_id: band.id).destroy
  end

  # Returns true if the current user is following the other user.
  def is_fan?(band)
    favorite_bands.include?(band)
  end

  # RSVP to concert.

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :correct_user, :concert_lists]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers, :favorite_bands]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :if_logged_in, only: :new

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @concert_lists = @user.concert_lists.paginate(page: params[:page], per_page: 10)
    @user.set_reputation_score
    if current_user?(@user)
      @concerts_users = @user.concerts_from_followed_users_who_like_the_same_genres
      @concerts_system = Array.new
      @concerts_system += @user.popular_concerts_from_users_who_like_the_same_genres unless @user.popular_concerts_from_users_who_like_the_same_genres.nil?
      @concerts_system += @user.top_recommended_concerts unless @user.top_recommended_concerts.nil?
      @concerts_system += @user.concerts_recommended_by_users_with_similar_tastes unless @user.concerts_recommended_by_users_with_similar_tastes.nil?
      @bands_popular = @user.popular_bands_that_play_genres_the_user_like
      @bands_with_good_concerts = @user.bands_with_good_concerts_that_play_genres_the_user_like
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    session[:band_id] = nil
    @user = User.new(user_params)

    if @user.save
      genres = get_genres(genre_ids_params)
      set_genres(@user, genres)
      log_in @user
      flash[:success] = "Welcome to LiveJive!"
      redirect_to @user
    else
      render :new
    end
 
  end

  def update
    if @user.update_attributes(user_params)
      genres = get_genres(genre_ids_params)
      set_genres(@user, genres)
      flash[:success] = "User was successfully updated."
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User was successfully deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def favorite_bands
    @title = "Favorite Bands"
    @user  = User.find(params[:id])
    @bands = @user.favorite_bands.paginate(page: params[:page])
    @users = @bands
    render 'show_favorite_bands'
  end

  def concerts
    @title = "Concert RSVPs"
    @user  = User.find(params[:id])
    @concerts = @user.concerts.paginate(page: params[:page])
    @users = @concerts
    render 'show_concert_goings'
  end

  def concert_lists
    @concert_lists = @user.concert_lists.paginate(page: params[:page], per_page: 10)
  end

  private
    def set_genres(user, genres)
      genres.each do |genre|
        user.set_genre(genre)
      end
    end

    def get_genres(genre_ids)
      genres = Array.new
      genre_ids[:genre_ids].each do |genre_id|
        p genre_id
        p genres << Genre.find(genre_id.to_i) unless genre_id == ""
      end
      genres
    end

    def if_logged_in
      redirect_to root_url if logged_in?
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to user_login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.is_admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :year_of_birth, :email, :password, :city_of_birth)
    end

    def genre_ids_params
      params.require(:user).permit(genre_ids: [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_concert_list.html.erb
<li id="concert_list-<%= concert_list.id %>">
  <%= link_to gravatar_for(concert_list.list_owner, size: 50), concert_list.list_owner %>
  <span class="user"><%= link_to concert_list.list_owner.name, concert_list.list_owner %></span>
  <span class="content"><%= link_to concert_list.title, concert_list %></span>
  <span class="content"><%= concert_list.description %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(concert_list.created_at) %> ago.
  </span>
</li>

app/views/users/_feed.html.erb
<h3>Recommended Concerts</h3>
<% if @concerts_users.any? %>
  <div>
    <h4>By Followed Users</h4>
    <ol class="microposts">
      <%= render @concerts_users %>
    </ol>
  </div>
<% end %>
<% if @concerts_system.any? %>
  <div>
	<h4>By the System</h4>
	<ol class="microposts">
	<%= render @concerts_system %>
	</ol>
  </div>
<% end %>
<h3>Recommended Bands</h3>
<% if @bands_popular.any? %>
  <div>
	<h4>Popular Among Users</h4>
	<ol class="microposts">
	<%= render @bands_popular %>
	</ol>
  </div>
<% end %>
<% if @bands_with_good_concerts.any? %>
  <div>
	<h4>With Highly Rated Concerts</h4>
	<ol class="microposts">
	<%= render @bands_with_good_concerts %>
	</ol>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build(followed_id: @user.id), remote:true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year_of_birth %><br>
    <%= f.number_field :year_of_birth %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :city_of_birth %><br>
    <%= f.text_field :city_of_birth %>
  </div>
  <div class="field">
    <%= f.label :reputation_score %><br>
    <%= f.number_field :reputation_score %>
  </div>
  <div class="field">
    <%= f.label :is_admin? %><br>
    <%= f.check_box :is_admin? %>
  </div>
  <div class="field">
    <%= f.label :last_login_at %><br>
    <%= f.datetime_select :last_login_at %>
  </div>
  <div class="field">
    <%= f.label :current_login_at %><br>
    <%= f.datetime_select :current_login_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_new_concert_list.html.erb
<% if current_user?(@user) %>
	<div style="text-align: center;">
		<%= button_to "Create a new concert list", new_concert_list_url, 
      :class => "btn btn-primary", :method => :get %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote:true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <span class="user"><%= link_to user.name, user %></span>
  <% if user_or_band == "User" %>
	  <% if current_user.is_admin? && !current_user?(user) %>
	    | <%= link_to "Delete", user, method: :delete, data: { confirm: "You sure?" } %>
	  <% end %>
  <% end %>
  <span class="content">Reputation Score: <%= user.reputation_score %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(user.created_at) %> ago
  </span>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>
<h1>Update your user profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

	  	<%= f.label :city_of_birth %>
      <%= f.text_field :city_of_birth, class: 'form-control' %>

      <%= f.label :year_of_birth %>
      <%= f.text_field :year_of_birth, class: 'form-control' %>

      <div class="field">
        <%= f.label :genre_ids, "Genres Liked" %><br />
        <%= f.collection_select :genre_ids, Genre.order(:subgenre), :id, :subgenre, {}, { multiple: true } %>
      </div>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="microposts">
  <%= render @users.order('created_at DESC') %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'User Sign Up') %>
<h1>User Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :city_of_birth %>
      <%= f.text_field :city_of_birth, class: 'form-control' %>

      <%= f.label :year_of_birth %>
      <%= f.text_field :year_of_birth, class: 'form-control' %>

      <div class="field">
        <%= f.label :genre_ids, "Genres Liked" %><br />
        <%= f.collection_select :genre_ids, Genre.order(:subgenre), :id, :subgenre, {}, { multiple: true } %>
      </div>

      

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

    <br>

    <p>Already have an account? <%= link_to "Log in now!", user_login_path %></p>
    
    <p>Are you a band? <%= link_to "Band Sign Up", band_signup_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'users/gravatar' %>
      </section>
      <section class="stats">
        <%= render 'users/stats' %>
      </section>
      <section>
        <%= render 'users/profile' %>
      </section>
    </aside>
    <div class="col-md-8">
      <%= render 'follow_form' if logged_in? && user_or_band == "User" %>
    </div>
    <div class="col-md-8">
      <% if user_or_band == "User" %>
        <% if current_user?(@user) %>
          <%= render 'users/feed' %>
        <% else %>
          <%= render 'users/concert_list_handler' %>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <script type="text/javascript">
    window.location.href="/user_login"  // put your correct path in a string here
  </script>
<% end %>

app/views/users/show_favorite_bands.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span style="font-size: 14px; margin-top: 10px;"><b>Reputation Score:</b> <%= @user.reputation_score %></span>
      <span style="font-size: 14px; margin-top: 10px;"><%= link_to "view my profile", @user %></span>
    </section>
    <section class="stats">
      <%= render 'users/stats' %>
      <% if @bands.any? %>
        <div class="user_avatars">
          <% @bands.each do |band| %>
            <%= link_to gravatar_for(band, size: 30), band %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @bands.any? %>
      <ul class="users follow">
        <%= render @bands %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span style="font-size: 14px; margin-top: 10px;"><b>Reputation Score:</b> <%= @user.reputation_score %></span>
      <span style="font-size: 14px; margin-top: 10px;"><%= link_to "view my profile", @user %></span>
    </section>
    <section class="stats">
      <%= render 'users/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>