config/routes.rb
Rails.application.routes.draw do

  # root
  root 'static_pages#home'

  # signups
  get 'users/new'  => 'users#new', as: :user_signup
  post 'users'  => 'users#create'
  get 'bands/new'  => 'bands#new', as: :band_signup
  post 'bands'  => 'bands#create'

  # sessions
  get 'user_login' => 'sessions#user_login', as: :user_login
  post 'user_login' => 'sessions#user_create'
  get 'band_login' => 'sessions#band_login', as: :band_login
  post 'band_login' => 'sessions#band_create'
  delete 'logout' => 'sessions#destroy'
  resources :account_activations, only: [:edit]

  # password reset
  resources :user_password_resets, only: [:new, :create, :edit, :update]
  resources :band_password_resets, only: [:new, :create, :edit, :update]

  # main pages
  resources :concert_lists
  resources :concerts
  resources :bands, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :fans
    end
    collection do
      get :sorted_by_genre
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :favorite_bands, :concerts
      get :concert_lists
      get :feed
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :fanships, only: [:create, :destroy]
  resources :concert_goings, only: [:create, :edit, :update, :destroy]
  resources :genres
  resources :searches

  # static pages
  get  'home' => 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

end

app/models/concert.rb
class Concert < ActiveRecord::Base
	attr_accessor :band_tokens, :band_ids, :vip_tickets_how_many_left, :vip_tickets_price, :confort_how_many_left, :confort_price, :pavillion_tickets_how_many_left, :pavillion_tickets_price, :front_row_tickets_how_many_left, :front_row_tickets_price, :lounge_tickets_how_many_left, :lounge_tickets_price
	attr_reader :band_tokens

	has_many :lineups, dependent: :destroy
	has_many :bands, through: :lineups

	has_many :concert_goings, dependent: :destroy
	has_many :goers, through: :concert_goings

	has_many :recommendations, dependent: :destroy
	has_many :concert_lists, through: :recommendations
	
	has_many :tickets, dependent: :destroy

	validates :title, presence: true
	validates :description, presence: true
	validates :buy_tickets_website, presence: true

	def self.search(search)
	  if search
	    where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
	  else
	    all
	  end
	end

	def average_rating
  	ratings = Array.new
  	if concert_goings.any?
	  	concert_goings.each do |rsvp|
	  		ratings << rsvp.rating if rsvp.rating
	  	end
  	end
  	ratings.inject{ |sum, el| sum + el }.to_f / ratings.size
  end

	def set_ticket(ticket)
		tickets.create(ticket)
	end

	def set_lineup(band)
		lineups.create(band_id: band.id)
	end

	def band_tokens=(ids)
		self.band_ids = ids.split(",")
	end

	def bands_playing
		bands = Array.new
		self.lineups.each do |lineup|
			bands << lineup.band
		end
		bands
	end

	def band_in_concert?(band)
		bands_playing.include?(band)
	end

	def genres_played
		genres = Array.new
		self.bands_playing.each do |band|
			genres << band.plays_genres
		end
		genres.flatten.uniq
	end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :band_plays_genres
	has_many :bands, through: :band_plays_genres

	has_many :user_likes_genres
	has_many :users, through: :user_likes_genres

	def printable
		if self.genre == self.subgenre
        return self.genre
    else
      return [self.genre, self.subgenre].join(" (").concat(")")
    end
	end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]
  before_action :logged_in, only: [:index, :show, :edit, :update, :destroy]
  before_action :trusted_user, only: [:edit, :update]
  before_action :correct_band, only: [:edit, :update, :destroy]
  before_action :admin_user, only: :destroy

  def new_search
    @concert = Concert.new
  end

  def create_search
  end

  def search_results
  end

  def index
    @concerts = Concert.search(params[:search]).paginate(page: params[:page])
  end

  def show
    @concert_going = ConcertGoings.find_by(concert_id: @concert.id, goer_id: current_user.id) if user_or_band == "User"
  end

  def new
    @concert = Concert.new
  end

  def edit
    session[:return_to] ||= request.referer
  end

  def create
    @concert = Concert.new(concert_params)

    if @concert.save
      bands = get_bands(band_ids_params)
      set_lineups(@concert, bands)
      set_tickets(@concert)
      redirect_to @concert
      flash[:success] = 'Concert was successfully created.'
    else
      render :new
    end
  end

  def update
    if @concert.update(concert_params)
      erase_lineups(@concert)
      bands = get_bands(band_ids_params)
      set_lineups(@concert, bands)
      redirect_to session.delete(:return_to)
      flash[:success] = 'Concert was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @concert.destroy
    flash[:success] = 'Concert was successfully destroyed.'
    if user_or_band == "User"
      redirect_to concerts_url
    else
      redirect_to band_path(current_band)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:title, :description, :cdatetime, :location_name, :ccity, :buy_tickets_website)
    end

    def band_ids_params
      params.require(:concert).permit(band_ids: [])
    end

    def tickets_params
      params.require(:concert).permit(:vip_tickets_how_many_left, :vip_tickets_price, :confort_how_many_left, :confort_price, :pavillion_tickets_how_many_left, :pavillion_tickets_price, :front_row_tickets_how_many_left, :front_row_tickets_price, :lounge_tickets_how_many_left, :lounge_tickets_price)
    end

    def get_tickets
      vip = Hash.new
      confort = Hash.new
      pavillion = Hash.new
      front_row = Hash.new
      lounge = Hash.new
      vip[:tier] = "VIP"
      vip[:how_many_left] = tickets_params[:vip_tickets_how_many_left]
      vip[:price] = tickets_params[:vip_tickets_price]
      confort[:tier] = "Confort"
      confort[:how_many_left] = tickets_params[:confort_how_many_left]
      confort[:price] = tickets_params[:confort_price]
      pavillion[:tier] = "Pavillion"
      pavillion[:how_many_left] = tickets_params[:pavillion_tickets_how_many_left]
      pavillion[:price] = tickets_params[:pavillion_tickets_price]
      front_row[:tier] = "Front Row"
      front_row[:how_many_left] = tickets_params[:front_row_tickets_how_many_left]
      front_row[:price] = tickets_params[:front_row_tickets_price]
      lounge[:tier] = "Lounge"
      lounge[:how_many_left] = tickets_params[:lounge_tickets_how_many_left]
      lounge[:price] = tickets_params[:lounge_tickets_price]
      [vip, confort, pavillion, front_row, lounge]
    end

    def set_tickets(concert)
      get_tickets.each do |ticket|
        concert.set_ticket(ticket)
      end
    end

    def get_bands(band_ids)
      bands = Array.new
      band_ids[:band_ids].each do |band_id|
        p band_id
        p bands << Band.find(band_id.to_i) unless band_id == ""
      end
      bands
    end

    def set_lineups(concert, bands)
      bands.each do |band|
        concert.set_lineup(band)
      end
    end

    def erase_lineups(concert)
      concert.lineups.each do |lineup|
        lineup.destroy
      end
    end

    # Confirms a logged-in.
    def logged_in
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to band_login_url
      end
    end

    # Confirms the correct band.
    def correct_band
      if user_or_band == "Band"
        redirect_to(root_url) unless @concert.band_in_concert?(current_band)
      else
        admin_user
      end
    end

    # Confirms an admin user.
    def admin_user
      if user_or_band == "User"
        redirect_to(root_url) unless current_user.is_admin?
      end
    end

    def trusted_user
      if user_or_band == "User"
        redirect_to(root_url) unless current_user.can_edit_concerts?
      end
    end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
	def pre_band_ids
		band_ids = Array.new
		@concert.lineups.each do |lineup|
			band_ids << lineup.band_id.to_s
		end
		band_ids
	end

	def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end

  def any_reviews?
    @concert.concert_goings.each do |rsvp|
      return true if rsvp.review
    end
    false
  end

  def any_tickets?
    @concert.tickets.any?
  end

  def average_rating
  	ratings = Array.new
  	@concert.concert_goings.each do |rsvp|
  		ratings << rsvp.rating if rsvp.rating
  	end
  	ratings.inject{ |sum, el| sum + el }.to_f / ratings.size
  end

  def range_arr(max)
  	range = Array.new
  	max.times { |n| range << n + 1 }
  	range
  end
end

app/views/concerts/_cancel_rsvp.html.erb
<%= form_for(current_user.concert_goings.find_by(concert_id: @concert.id), html: { method: :delete }, remote: true) do |f| %>
  <div style="text-align: center;">
    <%= f.submit "Cancel RSVP", class: "btn", style: "width: 400px;" %>
  </div>
<% end %>

app/views/concerts/_concert.html.erb
<li id="micropost-<%= concert.id %>">
	<span class="concert">
	<%= link_to concert.title, concert %>
		<% if user_or_band == "Band" %>
			<% if current_band.plays_in_concert?(concert) %>
				| <%= link_to "Edit", edit_concert_path(concert) %>
				| <%= link_to "Delete", concert, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
			<% elsif user_or_band == "User" %>
			<% if current_user.can_edit_concerts? || current_user.is_admin? %>
				| <%= link_to "Edit", edit_concert_path(concert) %>
			<% end %>
			<% if current_user.is_admin? %>
				| <%= link_to "Delete", concert, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
		<% end %>
	</span>
	<span class="content_concert">
		<%= concert.ccity %>
	</span>
	<span class="timestamp_concert">
		<%= concert.cdatetime.to_formatted_s(:long_ordinal) %>
	</span>
</li>

app/views/concerts/_concert_goings_form.html.erb
<% if user_or_band == "User" %>
  <div id="follow_form">
  <% if current_user.is_going_to?(@concert) %>
    <%= render 'cancel_rsvp' %>
  <% else %>
    <%= render 'rsvp' %>
  <% end %>
  </div>
<% end %>

app/views/concerts/_concert_review.html.erb
<% if @concert.cdatetime < Time.now %>
	<h2>Was the concert good?</h2>
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	    <%= form_for @concert_going do |f| %>
	      <%= render 'shared/concert_going_error_messages' %>

	      <%= f.label :review %>
	      <%= f.text_area :review, class: 'form-control' %>

	      <%= f.label :rating %>
	      <%= f.select :rating, options_for_select([ 1 ,2 ,3, 4, 5 ]), class: 'form-control' %>

	      <%= f.submit "Review Concert", class: "btn btn-primary" %>
	    <% end %>
	  </div>
	</div>
<% end %>

app/views/concerts/_concert_review_form.html.erb
<div id="review_form">
<% if current_user.is_going_to?(@concert) %>
	<% if @concert.cdatetime < Time.now %>
		<h2>Was the concert good?</h2>
		<div class="row">
		  <div class="col-md-6 col-md-offset-3">
		    <%= form_for @concert_going do |f| %>
		      <%= render 'shared/concert_going_error_messages' %>

		      <%= f.label :review %>
		      <%= f.text_area :review, class: 'form-control' %>

		      <%= f.label :rating %>
		      <%= f.select :rating, options_for_select([ 1 ,2 ,3, 4, 5 ]), class: 'form-control', include_blank: true %>

		      <%= f.submit "Review Concert", class: "btn btn-primary" %>
		    <% end %>
		  </div>
		</div>
	<% end %>
<% end %>
</div>

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cdate %><br>
    <%= f.date_select :cdate %>
  </div>
  <div class="field">
    <%= f.label :ctime %><br>
    <%= f.time_select :ctime %>
  </div>
  <div class="field">
    <%= f.label :location_name %><br>
    <%= f.text_field :location_name %>
  </div>
  <div class="field">
    <%= f.label :ccity %><br>
    <%= f.text_field :ccity %>
  </div>
  <div class="field">
    <%= f.label :buy_tickets_website %><br>
    <%= f.text_field :buy_tickets_website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/_rsvp.html.erb
<%= form_for(current_user.concert_goings.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :concert_id, @concert.id %></div>
  <div style="text-align: center;">
    <%= f.submit "RSVP", class: "btn btn-primary", style: "width: 400px;" %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<% provide(:title, 'Edit Concert') %>
<h1>Edit Concert</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@concert) do |f| %>
      <%= render 'shared/concert_error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 7 %>

      <%= f.label :buy_tickets_website %>
      <%= f.text_field :buy_tickets_website, class: 'form-control' %>

      <%= f.label :cdatetime, "Date and Time" %>
      <%= f.datetime_select :cdatetime, class: 'form-control' %>

      <%= f.label :location_name %>
      <%= f.text_field :location_name, class: 'form-control' %>

      <%= f.label :ccity, "City" %>
      <%= f.text_field :ccity, class: 'form-control' %>

		  <div class="field">
				<%= f.label :band_ids, "Lineup" %><br />
  			<%= f.collection_select :band_ids, Band.order(:name), :id, :name, {}, { multiple: true } %>
			</div>
	
      <%= f.submit "Create concert", class: "btn btn-primary" %>
    <% end %>

    <br>

    <%= link_to "Show all concerts", concerts_path %>
  </div>
</div>

app/views/concerts/index.html.erb
<% provide(:title, 'All Concerts') %>
<h1>All Concerts</h1>

<%= form_tag concerts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], { style: "width: 200px;" } %>
    <br>
    <%= submit_tag "Search", { name: nil, style: "width: 200px; margin-top: -1px;" } %>
  </p>
<% end %>
<p><%= link_to "Advanced Search", new_search_path %></p>

<%= will_paginate %>

<ul class="users">
  <%= render @concerts.order('cdatetime DESC') %>
</ul>

<%= will_paginate %>

app/views/concerts/new.html.erb
<% provide(:title, 'New Concert') %>
<h1>New Concert</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@concert) do |f| %>
      <%= render 'shared/concert_error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 7 %>

      <%= f.label :buy_tickets_website %>
      <%= f.text_field :buy_tickets_website, class: 'form-control' %>

      <%= f.label :cdatetime, "Date and Time" %>
      <%= f.datetime_select :cdatetime, class: 'form-control' %>

      <%= f.label :location_name %>
      <%= f.text_field :location_name, class: 'form-control' %>

      <%= f.label :ccity, "City" %>
      <%= f.text_field :ccity, class: 'form-control' %>

		  <div class="field">
				<%= f.label :band_ids, "Lineup" %><br />
  			<%= f.collection_select :band_ids, Band.order(:name), :id, :name, {}, { multiple: true } %>
			</div>
	   
      <div class="field">
      <strong>VIP Tickets</strong>
        <br><em>How many: </em><%= f.select :vip_tickets_how_many_left, options_for_select(range_arr(1000)), class: 'form-control' %>
        <em>Price: </em><%= f.select :vip_tickets_price, options_for_select(range_arr(1000)), class: 'form-control' %>
      </div>
          
      <div class="field">
        <strong>Confort Tickets</strong>
        <br><em>How many: </em><%= f.select :confort_how_many_left, options_for_select(range_arr(1000)), class: 'form-control' %>
        <em>Price: </em><%= f.select :confort_price, options_for_select(range_arr(1000)), class: 'form-control' %>
      </div>

      <div class="field">
        <strong>Pavillion Tickets</strong>
        <br><em>How many: </em><%= f.select :pavillion_tickets_how_many_left, options_for_select(range_arr(1000)), class: 'form-control' %>
        <em>Price: </em><%= f.select :pavillion_tickets_price, options_for_select(range_arr(1000)), class: 'form-control' %>
      </div>

      <div class="field">
        <strong>Front Row Tickets</strong>
        <br><em>How many: </em><%= f.select :front_row_tickets_how_many_left, options_for_select(range_arr(1000)), class: 'form-control' %>
        <em>Price: </em><%= f.select :front_row_tickets_price, options_for_select(range_arr(1000)), class: 'form-control' %>
      </div>

      <div class="field">
        <strong>Lounge Tickets</strong>
        <br><em>How many: </em><%= f.select :lounge_tickets_how_many_left, options_for_select(range_arr(1000)), class: 'form-control' %>
        <em>Price: </em><%= f.select :lounge_tickets_price, options_for_select(range_arr(1000)), class: 'form-control' %>
      </div>

      <%= f.submit "Create concert", class: "btn btn-primary" %>
    <% end %>

    <br>

    <%= link_to "Show all concerts", concerts_path %>
  </div>
</div>

app/views/concerts/new_search.html.erb
<% provide(:title, 'Concerts - Search') %>
<h1>Concerts - Search</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @concert, url: search_concerts_path, method: :post do |f|%>

      <%= f.label :keywords %>
      <%= f.text_field :keywords, class: 'form-control' %>

      <%= f.label :from_date, "From" %>
      <%= f.datetime_select :from_date, class: 'form-control' %>

      <%= f.label :to_date, "To" %>
      <%= f.datetime_select :to_date, class: 'form-control' %>

      <%= f.label :ccity, "City" %>
      <%= f.text_field :ccity, class: 'form-control' %>

	  <div class="field">
		<%= f.label :genre_ids, "Lineup" %><br />
		<%= f.collection_select :genre_ids, Genre.order(:subgenre), :id, :subgenre, {}, { multiple: true } %>
	</div>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>

    <br>

    <%= link_to "Show all concerts", concerts_path %>
  </div>
</div>

app/views/concerts/search_results.html.erb
search_results.html.erb

app/views/concerts/show.html.erb
<% provide(:title, @concert.title) %>
<h1><%= @concert.title %></h1>

<%= render 'concert_goings_form' if logged_in? && user_or_band == "User" %>

<ul class="users">
  <li>
    <strong>Description:</strong>
    <%= @concert.description %>
  </li>
  <% unless average_rating.nan? %>
    <li>
      <strong>Average Rating:</strong>
      <%= average_rating %>
    </li>
  <% end %>
  <li>
    <strong>Buy Tickets:</strong>
    <%= link_to @concert.buy_tickets_website, url_with_protocol(@concert.buy_tickets_website), :target => "_blank" %>
  </li>
  <li>
    <strong>Location:</strong>
    <%= @concert.location_name %>
  </li>
  <li>
    <strong>Date and Time:</strong>
    <%= @concert.cdatetime.to_formatted_s(:long_ordinal) %>
  </li>

  <li>
    <strong>Lineup:</strong>
    <ul>
      <% @concert.bands_playing.each do |band| %>
        <li>
          <%=link_to band.name, band %>
        </li>
      <% end %>
    </ul>
  </li>

  <li>
    <strong>Genres Played:</strong>
    <ul>
      <% @concert.genres_played.each do |genre| %>
        <li>
          <%= genre %>
        </li>
      <% end %>
    </ul>
  </li>
  <li>
    <% if any_tickets? %>
      <strong>Tickets:</strong>
      <ul>
        <% @concert.tickets.each do |ticket| %>
          <% if ticket.tier %>
            <li>
              <strong><%= ticket.tier %></strong>
            </li>
            <ul>
              <li>
                <strong>Price:</strong>
                <%= ticket.price %>
              </li>
              <li>
                <strong>How many left:</strong>
                <%= ticket.how_many_left %>
              </li>
            </ul>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </li>
  <% if any_reviews? %>
    <li>
      <strong>User Reviews:</strong>
      <ul>
        <% @concert.concert_goings.each do |rsvp| %>
          <% if rsvp.review || rsvp.rating %>
            <li>
              <ul>
                <li>
                  <strong>Reviewer:</strong>
                  <%= link_to rsvp.goer.name, rsvp.goer %>
                </li>
                <% if rsvp.rating %>
                  <li>
                    <strong>Rating:</strong>
                    <%= rsvp.rating %>
                  </li>
                <% end %>
                <% if rsvp.review %>
                  <li>
                    <strong>Review:</strong>
                    <%= rsvp.review %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>
      </ul>
    </li>
  <% end %>

  <%= render 'concert_review_form' if logged_in? && user_or_band == "User" %>

  <br>

  <li>
    <%= link_to "Show all concerts", concerts_path %>
  </li>
</ul>