config/routes.rb
Rails.application.routes.draw do

  # root
  root 'static_pages#home'

  # signups
  get 'users/new'  => 'users#new', as: :user_signup
  post 'users'  => 'users#create'
  get 'bands/new'  => 'bands#new', as: :band_signup
  post 'bands'  => 'bands#create'

  # sessions
  get 'user_login' => 'sessions#user_login', as: :user_login
  post 'user_login' => 'sessions#user_create'
  get 'band_login' => 'sessions#band_login', as: :band_login
  post 'band_login' => 'sessions#band_create'
  delete 'logout' => 'sessions#destroy'
  resources :account_activations, only: [:edit]

  # password reset
  resources :user_password_resets, only: [:new, :create, :edit, :update]
  resources :band_password_resets, only: [:new, :create, :edit, :update]

  # main pages
  resources :concert_lists
  resources :concerts
  resources :bands, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :fans
    end
    collection do
      get :sorted_by_genre
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :favorite_bands, :concerts
      get :concert_lists
      get :feed
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :fanships, only: [:create, :destroy]
  resources :concert_goings, only: [:create, :edit, :update, :destroy]
  resources :genres
  resources :searches

  # static pages
  get  'home' => 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token, :genre_ids

  before_save  :downcase_email
  before_create :create_activation_digest

	has_many :lineups
	has_many :concerts, through: :lineups

	has_many :band_plays_genres
	has_many :genres, through: :band_plays_genres
	
	has_many :fanships, dependent: :destroy
	has_many :fans, through: :fanships

	has_secure_password

  before_save { self.email = email.downcase }

  validates :bandname,  presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :website,  presence: true, length: { maximum: 50 }

  validates :bio,  presence: true, length: { maximum: 1000 }

  def set_genre(genre)
    band_plays_genres.create(genre_id: genre.id)
  end

  def reset_genres
    self.band_plays_genres.each do |band_plays_genre|
      band_plays_genre.destroy
    end
  end

  def plays_genre?(genre)
    self.genres.include?(genre)
  end

  # Genres that band plays.
  def plays_genres
    genres = Array.new
    self.genres.each do |genre|
      genres << genre.printable
    end
    genres.uniq
  end

  # Bands plays in concert?
  def plays_in_concert?(concert)
    concert.lineups.each do |lineup|
      return true if self.lineups.include? (lineup)
    end
    false
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Band.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = Band.new_token
    update_attribute(:remember_digest, Band.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a band.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:identity_confirmed?, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    BandMailer.account_activation(self).deliver!
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = Band.new_token
    update_attribute(:reset_digest,  Band.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    BandMailer.password_reset(self).deliver!
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

    private
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = Band.new_token
      self.activation_digest = Band.digest(activation_token)
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy, :correct_band]
  before_action :logged_in_band, only: [:index, :edit, :update, :destroy]
  before_action :correct_band, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :if_logged_in, only: :new

  def index
    @bands = Band.paginate(page: params[:page])
  end

  def sorted_by_genre
    @bands = Band.paginate(page: params[:page])
    @genres = Genre.all
  end

  def show
    @concerts = @band.concerts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @band = Band.new
  end

  def edit
  end

  def create
    session[:user_id] = nil
    @band = Band.new(band_params)

    if @band.save
      genres = get_genres(genre_ids_params)
      set_genres(@band, genres)
      @band.send_activation_email
      flash[:info] = "LiveJive must verify your identity. Please check your email."
      redirect_to band_login_url
    else
      render :new
    end
  end

  def update
    if @band.update_attributes(band_params)
      genres = get_genres(genre_ids_params)
      @band.reset_genres
      set_genres(@band, genres)
      flash[:success] = "Band was successfully updated."
      redirect_to @band
    else
      render :edit
    end
  end

  def destroy
    @band.destroy
    flash[:success] = "Band was successfully deleted."
    redirect_to bands_url
  end

  def fans
    @title = "Fans"
    @band  = Band.find(params[:id])
    @bands = @band.fans.paginate(page: params[:page])
    render 'show_fans'
  end

  private

    def set_genres(band, genres)
      genres.each do |genre|
        band.set_genre(genre)
      end
    end

    def get_genres(genre_ids)
      genres = Array.new
      genre_ids[:genre_ids].each do |genre_id|
        p genre_id
        p genres << Genre.find(genre_id.to_i) unless genre_id == ""
      end
      genres
    end

    def if_logged_in
      redirect_to root_url if logged_in?
    end

    # Confirms a logged-in band.
    def logged_in_band
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to band_login_url
      end
    end

    # Confirms the correct band.
    def correct_band
      redirect_to(root_url) unless current_band?(@band)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.is_admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:bandname, :name, :bio, :website, :email, :password)
    end

    def genre_ids_params
      params.require(:band).permit(genre_ids: [])
    end
end

app/helpers/bands_helper.rb
module BandsHelper
  # Returns the Gravatar for the given band.
  def gravatar_for(band, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(band.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: band.name, class: "gravatar")
  end
end

app/views/bands/_band.html.erb
<li id="micropost-<%= band.id %>">
	<%= link_to gravatar_for(band, size: 50), band %>
	<span class="user"><%= link_to band.name, band %>
		<% if user_or_band == "User" %>
			<% if current_user.is_admin? && !current_band?(band) %>
				| <%= link_to "Delete", band, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
		<% end %>
	</span>
	<span class="content"><%= band.bio %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(band.created_at) %> ago
  </span>
</li>

app/views/bands/_become_fan_form.html.erb
<% if user_or_band == "User" %>
  <div id="follow_form">
  <% if current_user.is_fan?(@band) %>
    <%= render 'undo_become_fan' %>
  <% else %>
    <%= render 'become_fan' %>
  <% end %>
  </div>
<% end %>

app/views/bands/_concerts.html.erb
<% if @band.concerts.any? %>
	<h3>Concerts [<%= @band.concerts.count %>]</h3>
	<ol class="microposts">
		<%= render @concerts %>
	</ol>
	<%= will_paginate @concerts %>
<% end %>

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bandname %><br>
    <%= f.text_field :bandname %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :identity_confirmed? %><br>
    <%= f.check_box :identity_confirmed? %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/_gravatar.html.erb
<h1>
	<%= gravatar_for @band %>
	<%= @band.name %>
	<span style="font-size: 14px; margin-top: 10px;"><b>Concerts:</b> <%= @band.concerts.count %></span>
</h1>

app/views/bands/_new_concert.html.erb
<% if current_band?(@band) %>
	<div style="text-align: center;">
		<%= button_to "Create a new concert", new_concert_url, 
      :class => "btn btn-primary", :method => :get %>
	</div>
<% end %>

app/views/bands/_profile.html.erb
<ul class="users">
  <li>
    <strong>Bandname:</strong>
    <%= @band.bandname %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @band.name %>
  </li>

  <li>
    <strong>Bio:</strong>
    <%= @band.bio %>
  </li>

  <li>
    <strong>Website:</strong>
    <%= link_to @band.website, url_with_protocol(@band.website), :target => "_blank" %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= link_to @band.email, "maito:#{@band.email}", :target => "_blank" %>
  </li>
  <li>
    <strong>Genres Played:</strong>
    <ul>
      <% @band.plays_genres.each do |genre| %>
        <li>
          <%= genre %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/bands/_stats.html.erb
<% @band ||= current_band %>
<div class="stats">
  <a href="<%= fans_band_path(@band) %>">
    <strong id="fans" class="stat">
      <%= @band.fans.count %>
    </strong>
    Fans
  </a>
</div>

app/views/bands/_undo_become_fan.html.erb
<%= form_for(current_user.fanships.find_by(band_id: @band.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "I'm not a fan anymore", class: "btn" %>
<% end %>

app/views/bands/edit.html.erb
<% provide(:title, "Settings") %>
<h1>Update your band profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@band) do |f| %>
      <%= render 'shared/band_error_messages' %>

      <%= f.label :bandname %>
      <%= f.text_field :bandname, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>

      <%= f.label :bio, "Short Bio" %>
      <%= f.text_area :bio, class: 'form-control', rows: 7 %>

      <div class="field">
        <%= f.label :genre_ids, "Genres" %><br />
        <%= f.collection_select :genre_ids, Genre.order(:subgenre), :id, :subgenre, {}, { multiple: true } %>
      </div>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @band %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/bands/index.html.erb
<% provide(:title, 'Bands - Sorted By Creation Date') %>
<h1>Bands - Sorted By Creation Date</h1>

<%= will_paginate %>

<ul class="microposts">
  <%= render @bands.order('created_at DESC') %>
</ul>

<%= will_paginate %>

app/views/bands/show.html.erb
<% provide(:title, @band.name) %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'bands/gravatar' %>
      </section>
      <section class="stats">
        <%= render 'bands/stats' %>
      </section>
      <section>
        <%= render 'bands/profile' %>
      </section>
    </aside>
    <div class="col-md-8">
      <%= render 'become_fan_form' if logged_in? && user_or_band == "User" %>
    </div>
    <div class="col-md-8">
      <% if user_or_band == "Band" %>
        <% if current_band?(@band) %>
          <%= render 'bands/new_concert' %>
        <% end %>
      <% end %>
      <%= render 'bands/concerts' %>
    </div>
  </div>
<% else %>
  <script type="text/javascript">
    window.location.href="/user_login"  // put your correct path in a string here
  </script>
<% end %>

app/views/bands/show_fans.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @band %>
      <h1><%= @band.name %></h1>
      <span style="font-size: 14px; margin-top: 10px;"><%= link_to "view profile", @band %></span>
    </section>
    <section class="stats">
      <%= render 'bands/stats' %>
      <% if @bands.any? %>
        <div class="user_avatars">
          <% @bands.each do |band| %>
            <%= link_to gravatar_for(band, size: 30), band %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @bands.any? %>
      <ul class="users follow">
        <%= render @bands %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/bands/sorted_by_genre.html.erb
<% provide(:title, 'Bands - Sorted By Genre') %>
<h1>Bands - Sorted By Genre</h1>

<%= will_paginate %>

<ul style="list-style-type: none;">
	<% @genres.each do |genre| %>
		<% if genre.bands.any? %>
			<li>
				<strong><%= genre.printable %></strong>
			</li>
			<ul class="microposts">		
				<% genre.bands.each do |band| %>
					<% if band.plays_genre?(genre) %>
						<%= render band %>
					<% end %>
				<% end %>
			</ul>
		<% end %>
	<% end %>
</ul>

<%= will_paginate %>