config/routes.rb
Rails.application.routes.draw do

  # root
  root 'static_pages#home'

  # signups
  get 'users/new'  => 'users#new', as: :user_signup
  post 'users'  => 'users#create'
  get 'bands/new'  => 'bands#new', as: :band_signup
  post 'bands'  => 'bands#create'

  # sessions
  get 'user_login' => 'sessions#user_login', as: :user_login
  post 'user_login' => 'sessions#user_create'
  get 'band_login' => 'sessions#band_login', as: :band_login
  post 'band_login' => 'sessions#band_create'
  delete 'logout' => 'sessions#destroy'
  resources :account_activations, only: [:edit]

  # password reset
  resources :user_password_resets, only: [:new, :create, :edit, :update]
  resources :band_password_resets, only: [:new, :create, :edit, :update]

  # main pages
  resources :concert_lists
  resources :concerts
  resources :bands, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :fans
    end
    collection do
      get :sorted_by_genre
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :favorite_bands, :concerts
      get :concert_lists
      get :feed
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :fanships, only: [:create, :destroy]
  resources :concert_goings, only: [:create, :edit, :update, :destroy]
  resources :genres
  resources :searches

  # static pages
  get  'home' => 'static_pages#home'
  get  'help' => 'static_pages#help'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

end

app/models/concert_list.rb
class ConcertList < ActiveRecord::Base
	has_many :recommendations
	has_many :concerts, through: :recommendations
	
	belongs_to :list_owner, class_name: "User"

	validates :list_owner_id, presence: true

	def set_recommendation(concert)
		recommendations.create(concert_id: concert.id)
	end

	def reset_recommendations
		self.recommendations.each do |recommendation|
			recommendation.destroy
		end
	end
end

app/controllers/concert_lists_controller.rb
class ConcertListsController < ApplicationController
  before_action :set_concert_list, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :only_user

  def index
    @concert_lists = ConcertList.all
  end

  def show
  end

  def new
    @concert_list = ConcertList.new
  end

  def edit
  end

  def create
    concert_list_params[:list_owner_id] = current_user.id
    @concert_list = ConcertList.new(concert_list_params)
    if @concert_list.save
      concerts = get_concerts(concert_ids_params)
      set_recommendations(@concert_list, concerts)
      redirect_to @concert_list, notice: 'Concert list was successfully created.'
    else
      render :new
    end
  end

  def update
    if @concert_list.update(concert_list_params)
      concerts = get_concerts(concert_ids_params)
      @concert_list.reset_recommendations
      set_recommendations(@concert_list, concerts)
      redirect_to @concert_list, notice: 'Concert list was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @concert_list.destroy
    redirect_to concert_lists_url, notice: 'Concert list was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert_list
      @concert_list = ConcertList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_list_params
      params.require(:concert_list).permit(:list_owner_id, :title, :description)
    end

    def concert_ids_params
      params.require(:concert_list).permit(concert_ids: [])
    end

    def get_concerts(concert_ids)
      concerts = Array.new
      concert_ids[:concert_ids].each do |concert_id|
        p concert_id
        p concerts << Concert.find(concert_id.to_i) unless concert_id == ""
      end
      concerts
    end

    def set_recommendations(concert_list, concerts)
      concerts.each do |concert|
        concert_list.set_recommendation(concert)
      end
    end

    # Confirms the correct user.
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to user_login_url
      end
    end

    def only_user
      redirect_to root_url if user_or_band == "Band"
    end
end

app/helpers/concert_lists_helper.rb
module ConcertListsHelper
end

app/views/concert_lists/_concert_list.html.erb
<li id="concert_list-<%= concert_list.id %>">
	<span class="content"><%= link_to concert_list.title, concert_list %>
		<% if user_or_band == "User" %>
			<% if current_user?(@user) %>
				| <%= link_to "Edit", edit_concert_list_url %>
			<% end %>
			<% if current_user.is_admin? || current_user?(@user) %>
				| <%= link_to "Delete", concert_list, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
		<% end %>
	</span>
	<span class="content"><%= concert_list.description %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(concert_list.created_at) %> ago
	</span>
</li>

app/views/concert_lists/_form.html.erb
<%= form_for(@concert_list) do |f| %>
  <% if @concert_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert_list.errors.count, "error") %> prohibited this concert_list from being saved:</h2>

      <ul>
      <% @concert_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_owner_id %><br>
    <%= f.number_field :list_owner_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concert_lists/edit.html.erb
<% provide(:title, 'Edit Concert List') %>
<h1>Edit Concert List</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@concert_list) do |f| %>
      <%= render 'shared/concert_list_error_messages' %>
			
      <%= hidden_field_tag :list_owner_id, current_user.id %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 7 %>

		  <div class="field">
				<%= f.label :concert_ids, "Concerts" %><br />
  			<%= f.collection_select :concert_ids, Concert.order(:title), :id, :title, {}, { multiple: true } %>
			</div>

      <%= f.submit "Edit concert list", class: "btn btn-primary" %>
    <% end %>

    <br>

    <%= link_to "Go back", user_path(current_user) %>
  </div>
</div>

app/views/concert_lists/index.html.erb
<h1>Listing concert_lists</h1>

<table>
  <thead>
    <tr>
      <th>List owner</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concert_lists.each do |concert_list| %>
      <tr>
        <td><%= concert_list.list_owner_id %></td>
        <td><%= concert_list.title %></td>
        <td><%= concert_list.description %></td>
        <td><%= link_to 'Show', concert_list %></td>
        <td><%= link_to 'Edit', edit_concert_list_path(concert_list) %></td>
        <td><%= link_to 'Destroy', concert_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert list', new_concert_list_path %>

app/views/concert_lists/new.html.erb
<% provide(:title, 'New Concert List') %>
<h1>New Concert List</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@concert_list) do |f| %>
      <%= render 'shared/concert_list_error_messages' %>
			
      <%= f.hidden_field :list_owner_id, value: current_user.id %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 7 %>

		  <div class="field">
				<%= f.label :concert_ids, "Concerts" %><br />
  			<%= f.collection_select :concert_ids, Concert.order(:title), :id, :title, {}, { multiple: true } %>
			</div>

      <%= f.submit "Create concert list", class: "btn btn-primary" %>
    <% end %>

    <br>

    <%= link_to "Go back", user_path(current_user) %>
  </div>
</div>

app/views/concert_lists/show.html.erb
<% provide(:title, @concert_list.title) %>
<h1><%= @concert_list.title %></h1>

<ul class="users">
  <li>
    <strong>Title:</strong>
    <%= @concert_list.title %>
  </li>
  <li>
    <strong>Description:</strong>
    <%= @concert_list.description %>
  </li>
  <li>
    <strong>List Owner:</strong>
    <%= link_to @concert_list.list_owner.name, @concert_list.list_owner %>
  </li>
  <li>
    <strong>Concerts:</strong>
    <ul>
      <% @concert_list.concerts.each do |concert| %>
        <li>
          <%=link_to concert.title, concert %>
        </li>
      <% end %>
    </ul>
  </li>
  
  <br>

  <li>
    <%= link_to "Go back", user_path(current_user) %>
  </li>
</ul>